#!/usr/bin/env node
/* build-seed.js - regenerate everything that is derived from data/companies.md.
 *
 *   node app/scripts/build-seed.js        (or: pnpm run seed)
 *
 * Two outputs, both GENERATED - never edit them by hand:
 *
 *   app/seed-companies.js   the snapshot the app ships, so it works offline
 *                           and on first run before "Update data" is clicked
 *   README.md               the preview table between the COMPANIES markers
 *
 * data/companies.md is the single source of truth. Uses the same parser the
 * browser uses - app/data.js.
 */
'use strict';

var fs = require('fs');
var path = require('path');
var CLData = require('../data.js');

var PREVIEW_COUNT = 20;

var appDir = path.join(__dirname, '..');
var repoDir = path.join(appDir, '..');
var datasetPath = path.join(repoDir, 'data', 'companies.md');
var readmePath = path.join(repoDir, 'README.md');
var outPath = path.join(appDir, 'seed-companies.js');

var rows = CLData.parseMarkdownTable(fs.readFileSync(datasetPath, 'utf8'));
if (!rows.length) {
  console.error('No rows parsed from ' + datasetPath + ' - refusing to write an empty seed.');
  process.exit(1);
}

// Keep the payload small: applyLevel/applyReason are recomputed at load time.
var slim = rows.map(function (r) {
  return {
    company: r.company, domain: r.domain, email: r.email, team: r.team,
    location: r.location, description: r.description, source: r.source,
    lastVerified: r.lastVerified
  };
});

var banner = [
  '/* seed-companies.js - GENERATED, do not edit by hand.',
  ' * Snapshot of data/companies.md so the app works offline / on first run.',
  ' * Regenerate: pnpm run seed',
  ' * Rows: ' + slim.length,
  ' */'
].join('\n');

fs.writeFileSync(
  outPath,
  banner + '\nwindow.CL_SEED_COMPANIES = ' + JSON.stringify(slim, null, 1) + ';\n',
  'utf8'
);

/* ------------------------------------------------------- README preview */

var START = '<!-- COMPANIES:START';
var END = '<!-- COMPANIES:END -->';

/** A cell must never break the table it lives in. */
function cell(value) {
  return String(value || '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

function previewTable(list) {
  var lines = [
    '| Company | Role Email | Location | What they do |',
    '|---|---|---|---|'
  ];
  list.forEach(function (r) {
    lines.push('| ' + [
      cell(r.company), '`' + cell(r.email) + '`', cell(r.location), cell(r.description)
    ].join(' | ') + ' |');
  });
  return lines.join('\n');
}

// Show real application targets only: accommodation, EEO and anti-fraud
// inboxes are in the dataset for completeness, but they are not places to
// apply, and the app hides them too.
var applicable = rows.filter(function (r) { return r.applyLevel !== 'blocked'; });
var preview = applicable.slice(0, PREVIEW_COUNT);

var readme = fs.readFileSync(readmePath, 'utf8');
var startAt = readme.indexOf(START);
var endAt = readme.indexOf(END);

if (startAt === -1 || endAt === -1 || endAt < startAt) {
  console.error('No COMPANIES:START / COMPANIES:END markers in ' + readmePath +
                ' - skipped the README preview.');
  process.exitCode = 1;
} else {
  var header = START + ' - GENERATED by `pnpm run seed`. Edit data/companies.md, not this. -->';
  var block = [
    header,
    '',
    previewTable(preview),
    '',
    '**' + preview.length + ' of ' + applicable.length + ' companies shown.** The full list — with domains, ' +
    'team labels, source URLs and verification dates — is in ' +
    '[`data/companies.md`](data/companies.md).',
    '',
    END
  ].join('\n');

  fs.writeFileSync(readmePath, readme.slice(0, startAt) + block + readme.slice(endAt + END.length), 'utf8');
  console.log('Wrote ' + readmePath + ' (' + preview.length + '-row preview)');
}

var blocked = rows.filter(function (r) { return r.applyLevel === 'blocked'; }).length;
var warned = rows.filter(function (r) { return r.applyLevel === 'warn'; }).length;
console.log('Wrote ' + outPath);
console.log(slim.length + ' rows · ' + blocked + ' blocked (not for applications) · ' + warned + ' generic-inbox warnings');
